# Generated by Django 5.0.3 on 2024-04-10 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название базы')),
                ('archive', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл архива для базы')),
                ('last_data', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата создания файла конфига')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=250, verbose_name='Ключ доступа')),
                ('hwid', models.CharField(blank=True, max_length=25, null=True, verbose_name='HWID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('archive_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.archivebase')),
            ],
        ),
        migrations.AddField(
            model_name='archivebase',
            name='admin_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.key', verbose_name='Администратор базы'),
        ),
    ]
