# Generated by Django 5.0.3 on 2024-04-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название базы')),
                ('archive', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл архива для базы')),
                ('last_data', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата создания файла конфига')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=250, verbose_name='Ключ доступа')),
                ('hwid', models.CharField(blank=True, max_length=25, null=True, verbose_name='HWID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
        ),
    ]
