# Generated by Django 5.0.3 on 2024-04-20 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivebase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='key',
            name='archive_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.archivebase'),
        ),
        migrations.AddField(
            model_name='archivebase',
            name='admin_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.key', verbose_name='Администратор базы'),
        ),
    ]
