# Generated by Django 5.0.3 on 2024-04-22 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivebase',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файл архива для базы'),
        ),
        migrations.AlterField(
            model_name='key',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ключ доступа'),
        ),
    ]
