# Generated by Django 5.0.3 on 2024-04-20 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_keys', models.IntegerField(verbose_name='Количество ключей')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Название продукта')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Слаг')),
                ('image', models.ImageField(max_length=300, upload_to='', verbose_name='Изображение товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('download_link', models.URLField(verbose_name='Ссылка для скачивания')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.IntegerField(blank=True, null=True, verbose_name='Id подписки')),
                ('status', models.CharField(choices=[('rendering_payment', 'Ожидается оплата'), ('failed', 'Не удался'), ('completed', 'Выполнен'), ('canceld', 'Отменен')], default='rendering_payment', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('order_user_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_access', models.DateField(blank=True, null=True, verbose_name='Начало действия подписки')),
                ('expire_access', models.DateField(blank=True, null=True, verbose_name='Окончание действия подписки')),
                ('count_keys', models.IntegerField(blank=True, null=True, verbose_name='Количество ключей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.archivebase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subscription', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Название свойства')),
                ('days', models.IntegerField(blank=True, null=True, verbose_name='Количество дней')),
                ('price', models.IntegerField(verbose_name='Стоимость варианта подписки')),
                ('percent_for_key', models.IntegerField(blank=True, null=True, verbose_name='Какой процент стоимости для ключа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Срок подписки',
                'verbose_name_plural': 'Сроки подписки',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subscription_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subscriptionperiod'),
        ),
    ]
