# Generated by Django 5.0.3 on 2024-04-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionperiod',
            options={'ordering': ['price'], 'verbose_name': 'Срок подписки', 'verbose_name_plural': 'Сроки подписки'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subscription_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subscriptionperiod', verbose_name='Срок подписки'),
        ),
    ]
