# Generated by Django 5.0.3 on 2024-04-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_slug_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subscription', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='subscriptionperiod',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='shop.product', verbose_name='Продукт'),
        ),
    ]
