# Generated by Django 5.0.3 on 2024-04-11 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_subscription_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='subscription',
            name='begin_access',
            field=models.DateField(blank=True, null=True, verbose_name='Начало действия подписки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='count_keys',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ключей'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='expire_access',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание действия подписки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
