# Generated by Django 5.0.3 on 2024-04-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subscription_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subscription'),
        ),
    ]
